name: Test
on: 
  pull_request:
    branches:
      - main
jobs:
  jest-test:
    name: Jest Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Jest coverage report
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        package-manager: yarn
