name: CI
on: 
  pull_request:
    branches:
      - main
jobs:
  jest-test:
    name: Jest Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install
    - name: Jest Annotations & Coverage
      uses: mattallty/jest-github-action@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        test-command: "yarn test"