name: CI
on: 
  pull_request:
    branches:
      - main
jobs:
  jest-test:
    name: Jest Test
    runs-on: ubuntu-latest
    steps:
    - name: Jest Annotations & Coverage
      uses: mattallty/jest-github-action@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        test-command: "yarn test"